[build]
  command = "npm run build --workspace=client && npm run build --workspace=server"
  publish = "client/dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose", "mongodb-memory-server", "bcryptjs"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
